spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      encoding: UTF-8

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root : INFO
    dev : INFO
    org:
      springframework:
        web: INFO
        boot:
          autoconfigure: INFO
      hibernate : ERROR
debug: false

